configs:

  # Default config for editing ExaGO on newell
  newell-exago:
    launch-command: srun -A exasgd -p newell_shared -N 1 -n 2 -t '59:00' --pty bash

    modules:
      - vim
      - git

    commands:
      - cd ~/workspace/exago
      - pwd
      - rm -rf build install
      - ls
      - mkdir build install
      - source ./buildsystem/gcc-cuda/newellVariables.sh
      - source /share/apps/anaconda3/etc/profile.d/conda.sh

  marianas:
    launch-command: srun -A exasgd -p dl -N 1 -n 2 -t '59:00' --pty bash

aliases:
  n: newell-exago
  m: marianas
