#!/usr/bin/env bash

prompt()
{
  echo "[`git rev-parse --abbrev-ref HEAD`]-> "
}
dir=`pwd`
HISTFILE=$HOME/.git-explore-history

usage() { echo "Usage: $0 [-d directory] [-h history-file]"; exit 1; }

while getopts "d:" arg; do
  case $arg in
  h)
    HISTFILE=${OPTARG}
    ;;
  d)
    dir=${OPTARG}
    ;;
  *)
    usage
    ;;
  esac
done
shift $((OPTIND-1))

echo "Using directory $dir"
cd $dir

help_()
{
  echo 'Default special commands:
  hclear: Clear git-explore history
  a: add
  s: status
  ls: ls-files
  ck: checkout
  c: commit
  g: log --graph --color --oneline'
}

# Replace shortcuts with their expansions
r()
{
  echo $* \
    | sed -e 's/^s$/status /' -e 's/^s /status /' \
        -e 's/^ls$/ls-files /' -e 's/^ls /ls-files /' \
        -e 's/^ck /checkout /' \
        -e 's/^c$/commit /' \
        -e 's/^b$/branch/' -e 's/^b /branch /' \
        -e 's/^g$/log --graph --color --oneline /' \
        -e 's/^a /add /'
}

# Execute command in directory
e()
{
  (cd $dir && $*)
}

# Execute git command in directory
ge()
{
  e git $*
}

branch=`ge rev-parse --abbrev-ref HEAD`

while :
do
  read -e -p "`prompt`" input

  # Run special hooks
  case $input in
    h|help)
      help_
      continue
      ;;
    '')
      continue
      ;;
  esac

  # Run replacements on input commands
  input=`r $input`

  case $input in

    # Escape to run shell commands in the directory
    \!*)
      e `echo $input | sed 's/^!//'`
      ;;

    # Run everything else through git
    *)
      ge $input
      ;;
  esac
done
