#!/usr/bin/env bash

prompt()
{
  echo "[`git rev-parse --abbrev-ref HEAD`]-> "
}
exe=$0

usage() {
  echo "

  ------------------------

  Usage: $exe [directory]

  $exe:
  The shell for git commands. Every command is invoked via git unless explicitly
  ran through the shell with a leading '!'.

  ------------------------

  Interpreter commands:

  a     =  add
  s     =  status
  ls    =  ls-files
  ck    =  checkout
  c     =  commit
  g     =  log --graph --color --oneline'
  q     =  quit
  !cmd  =  Run \$cmd in shell

  ------------------------"
}

test $# -eq 1 && dir=$1
test $# -eq 0 && dir=`pwd`
test $# -gt 1 && { usage; exit 1; }

cd $dir
echo "Using directory $dir"

# Replace shortcuts with their expansions
r()
{
  echo $* \
    | sed -e 's/^s$/status /' -e 's/^s /status /' \
        -e 's/^ls$/ls-files /' -e 's/^ls /ls-files /' \
        -e 's/^ck /checkout /' \
        -e 's/^c$/commit /' \
        -e 's/^b$/branch/' -e 's/^b /branch /' \
        -e 's/^g$/log --graph --color --oneline /' \
        -e 's/^a /add /'
}

# Execute command in directory
e()
{
  ($*)
}

# Execute git command in directory
ge()
{
  e git $*
}

branch=`ge rev-parse --abbrev-ref HEAD`

while :
do
  read -e -p "`prompt`" input

  # Run special hooks
  case $input in
    q|quit)
      exit
      ;;
    h|help)
      usage
      continue
      ;;
    '')
      continue
      ;;
  esac

  # Run replacements on input commands
  input=`r $input`

  case $input in

    # Escape to run shell commands in the directory
    \!*)
      e `echo $input | sed 's/^!//'`
      ;;

    # Run everything else through git
    *)
      ge $input
      ;;
  esac
done
