#!/usr/bin/env perl

use warnings;
use strict;
use v5.10;
use Git::Repository;
use Path::Tiny;
use Term::Choose qw(choose);
use Term::UI;
use Cwd qw(cwd);

my $line = "------------------------------------------------------------------------";
sub doline {
  say $line;
}

my $worktree = "";
my $term = Term::ReadLine->new('GitExts');

if ($ENV{SQUASHER_GIT_DIR}) {
  $worktree = $ENV{SQUASHER_GIT_DIR};
} elsif (scalar @ARGV > 0) {
  $worktree = $ARGV[0];
} else {
  $worktree = &cwd();
}

doline();
say "Found working directory $worktree.";
doline();

my $repo = Git::Repository->new(work_tree=>$worktree);
my @modif = $repo->run('ls-files', '-m');

foreach (@modif) { say; }
doline();

my $good = $term->ask_yn(
  prompt => 'Add all these?',
  default => 'y',
);

if (!$good) {
  say "Select files you would like to add.";
  doline();
  @modif = choose(\@modif, {
      layout => 3,
      prompt => "Space to select, Enter to continue."
    });
}

if (scalar @modif == 0) {
  say "Nothing to do.";
  exit;
}

foreach my $f (@modif) {
  $repo->run('add', $f);
  say "Adding $f...";
}

my $good = $term->ask_yn(
  prompt => 'Want to commit?',
  default => 'y',
);

if ($good) {
  my $msg = $term->get_reply(
    prompt => 'Enter commit message',
  );
  $repo->run('commit', '-m', $msg);
}
